### ISSUE TITLE
wrong upgrades visible sometimes

### ISSUE THREAD

**Issue by Rsw783** [Rielk/RielksMelvorMods#11]
**Describe the bug**
When clicking the 'Upgrades' button sometimes you will see the options for a previously selected item.

**To Reproduce**

1. Hide all rooms (For ease of explanation)
2. Show a room
3. Choose a fixture to upgrade
4. Click upgrade
5. Go back
6. Make another room visible
7. Choose a fixture to upgrade
8. Click upgrade
9. Go back
10. Return back to that first upgradable fixture
11. The upgrades for the second fixture will be shown instead of the first fixture's
12. (Extra)Any other fixtures that have a 'Upgrades' button visible will also show the first fixtures recipes
13. (Extra)Selecting an unselected fixture in a visible room will swap the recipe that is stuck to that fixures

**Expected behavior**
the visible 'upgrades' section show display its own items, not those belonging to another

**Screenshots**
Correct here:
![first_item_is_correct](https://github.com/user-attachments/assets/aca233a5-362d-48cd-964c-30f7250df593)
Correct here:
![second_item_is_correct](https://github.com/user-attachments/assets/75411b25-ece5-4982-b733-06d6c6167584)
Is now wrong here:
![first_item_is_wrong](https://github.com/user-attachments/assets/94632fb9-81b2-4218-be66-ea6d9a33da28)

**Additional context**
Seemingly the room visibility option is what causes it to lose track of which upgrades to show. I don't have enough experience with JS to find the exact point unfortunately.
More specifically(presumably), whatever method the 'upgrades' button uses doesn't get sent that the selected fixture has changed

**Comment by Rielk** [comment]
Should be fixed now.
The commit e673e14 should have solved this for version 0.2.8
The upgrades panel was only displaying the last fixture clicked on and not updating to the correct fixture when the upgrades button was clicked.

(10/10 on the bug report btw. Very clear. Much appreciated.)
